In [1]:
import math

In [2]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.12/library/math.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The re

In [3]:
math.cos(22.5)

-0.8733046400935156

In [5]:
math.pi * 10

31.41592653589793

In [1]:
import math as m

In [2]:
m.cos(22.5)

-0.8733046400935156

In [4]:
import mod 

In [5]:
mod.show()

This is a module function.


In [6]:
import numpy as np

In [7]:
arr1 = np.array([1, 2, 3, 4, 5, 5])

In [9]:
print(arr1)

[1 2 3 4 5 5]


In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1[2]

np.int64(3)

In [12]:
arr1[2] = 100

In [13]:
arr1

array([  1,   2, 100,   4,   5,   5])

In [14]:
arr2 = np.array([2, 5, True,'ok', 10.5])

In [15]:
arr2

array(['2', '5', 'True', 'ok', '10.5'], dtype='<U32')

In [16]:
import time
time.time()

1767760025.818635

In [17]:
l = [1, 2, 3, 4, 5]
l * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
arr1 * 2

array([  2,   4, 200,   8,  10,  10])

In [20]:
# time difference for list and array

In [21]:
l1 = list(range(1, 1000000))
a = np.array(l1)

In [22]:
# list time
start_time = time.time()
newl = [x*2 for x in l1]
end_time = time.time()
time_list = end_time - start_time
print("time taken by list:", time_list)

time taken by list: 0.03344464302062988


In [23]:
# array time
start_time = time.time()
newa = a * 2
end_time = time.time()
time_array = end_time - start_time
print("time taken by array:", time_array)

time taken by array: 0.002106189727783203


In [24]:
time_list / time_array

15.879216662893366

In [25]:
arr1

array([  1,   2, 100,   4,   5,   5])

In [26]:
arr1[1:4]

array([  2, 100,   4])

In [27]:
# 2d array

In [28]:
arr = np.array([[1, 4, 3], [5, 2, 9], [12, 4, 78],
                [0, -1, 5]])

In [29]:
arr

array([[ 1,  4,  3],
       [ 5,  2,  9],
       [12,  4, 78],
       [ 0, -1,  5]])

In [30]:
arr.ndim

2

In [31]:
arr.shape

(4, 3)

In [32]:
arr[1:3, 0:2]

array([[ 5,  2],
       [12,  4]])

In [33]:
arr[[0, 1, 3], 0:2]

array([[ 1,  4],
       [ 5,  2],
       [ 0, -1]])

In [35]:
arr[2,2] = 100

In [36]:
arr

array([[  1,   4,   3],
       [  5,   2,   9],
       [ 12,   4, 100],
       [  0,  -1,   5]])

In [37]:
arr.reshape(3, 4)

array([[  1,   4,   3,   5],
       [  2,   9,  12,   4],
       [100,   0,  -1,   5]])

In [38]:
arr.reshape(6, 2)

array([[  1,   4],
       [  3,   5],
       [  2,   9],
       [ 12,   4],
       [100,   0],
       [ -1,   5]])

In [39]:
arr.flatten()

array([  1,   4,   3,   5,   2,   9,  12,   4, 100,   0,  -1,   5])

In [40]:
# linear algebra

In [41]:
arr = np.array([[1, 4, 3], [5, 2, 9], [12, 4, 78]])

In [42]:
arr

array([[ 1,  4,  3],
       [ 5,  2,  9],
       [12,  4, 78]])

In [43]:
np.linalg.inv(arr)

array([[-0.11764706,  0.29411765, -0.02941176],
       [ 0.27647059, -0.04117647, -0.00588235],
       [ 0.00392157, -0.04313725,  0.01764706]])

In [44]:
np.linalg.det(arr)

np.float64(-1019.9999999999998)

In [45]:
np.linalg.eig(arr)

EigResult(eigenvalues=array([79.01416522, -2.73467736,  4.72051215]), eigenvectors=array([[-0.04423509, -0.75799102, -0.66586771],
       [-0.11879083,  0.64726659, -0.73105101],
       [-0.99193346,  0.08059518,  0.14894504]]))